---
- name: Configure Zabbix checks for testserver
  hosts: zabbix
  gather_facts: false

  vars:
    target_host: "testserver"

  tasks:
    - name: Link monitoring templates to host
      zabbix.zabbix.zabbix_host:
        state: present
        host: "{{ target_host }}"
        hostgroups:
          - "Linux servers"
        interfaces:
          - type: agent
            ip: "{{ hostvars['testserver']['ansible_host'] }}"
            dns: ""
            useip: true
            port: 10050
        templates:
          - "ICMP Ping"
          - "Apache by HTTP"
          - "Linux by Zabbix agent"

