[monitoring]
zabbix ansible_host=192.168.122.107 ansible_connection=httpapi ansible_network_os=zabbix.zabbix.zabbix ansible_httpapi_use_ssl=false ansible_httpapi_validate_certs=false 

 
[admin]
tra ansible_host=192.168.122.235

[servers]
testserver ansible_host=192.168.122.136

[automation]
aap ansible_host=192.168.122.135

