---
- name: Install and configure zabbix agent
  hosts: all
  vars_files: 
    - myvars
  tasks:
  
    - name: download Zabbix repo key
      ansible.builtin.get_url:
        url: https://repo.zabbix.com/zabbix-official-repo.key
        dest: /home/ansible/
        mode: '0640'

    - name: import key
      ansible.builtin.rpm_key:
        state: present
        key: /home/ansible/zabbix-official-repo.key
      ignore_errors: true
      
    - name: Install zabbix repo
      ansible.builtin.package:
        name: https://repo.zabbix.com/zabbix/7.4/release/rhel/9/noarch/zabbix-release-latest.el9.noarch.rpm
        state: present
      
    - name: Install zabbix2 agent package
      ansible.builtin.package:
        name: zabbix-agent2
        state: present
 
    - name: add zabbix dir (why isn't this created by the rpm?) 
      ansible.builtin.file:
        path: /etc/zabbix
        state: directory
        mode: 0660
  
    - name: Configure zabbix agent
      ansible.builtin.template:
        src: zabbix_agentd.conf.j2
        dest: /etc/zabbix/zabbix_agentd.conf
  
  handlers:
    - name: restart zabbix-agent
      ansible.builtin.service:
        name: zabbix-agent
        state: restarted
