---
- name: Create a project
  hosts: localhost
  vars_files:
    - myvars
  connection: local
  gather_facts: false
  tasks:
    - name: Create Machine Credential
      ansible.controller.credential:
        name: "{{ credential_vault_name }}"
        organization: Default
        credential_type: Vault
        inputs:
          vault_password: "{{ vault_password }}"
        controller_host: "{{ controller_host }}"
        controller_username: admin
        controller_password: "{{ _controller_password_ }}"
