---
- name: Create a project
  hosts: localhost
  vars_files:
    - myvars
  connection: local
  gather_facts: false
  tasks:
    - name: Create the Test Project
      ansible.controller.project:
        name: "{{ project_name }}"
        scm_type: git
        scm_url: "{{ git_url }}"
        scm_branch: main
        scm_clean: true
        organization: Default
        wait: true
        controller_host: "{{ controller_host }}"
        controller_username: admin
        controller_password: "{{ _controller_password_ }}"
        validate_certs: false
