---
- name: Create a project
  hosts: localhost
  vars_files:
    - myvars
  connection: local
  gather_facts: false
  tasks:
    - name: Create Machine Credential
      ansible.controller.credential:
        name: "{{ credential_name }}"
        organization: Default
        credential_type: Machine
        inputs:
          username: "{{ machine_user }}"
          password: "{{ machine_password }}"
          become_method: sudo
          become_password: "{{ machine_password }}"
        controller_host: "{{ controller_host }}"
        controller_username: admin
        controller_password: "{{ _controller_password_ }}"
